import { resolve, join } from "node:path";
import postcss from "postcss";
import tailwindcss from "tailwindcss";

const root = resolve(import.meta.dir, "..");
export async function buildCss() {
  const globals = await Bun.file(join(root, "src/onyx/styles/globals.css")).text();
  const bedrock = await Bun.file(join(root, "src/bedrock/styles.css")).text();
  const codiconPackage = resolve(Bun.resolveSync("@vscode/codicons/package.json", root), "..");
  for (const license of ["LICENSE", "LICENSE-CODE"]) {
    await Bun.write(join(root, `dist/codicons-${license}`), await Bun.file(join(codiconPackage, license)).text());
  }
  await Bun.write(join(root, "dist/codicons-NOTICE"), "Codicons by Microsoft (https://github.com/microsoft/vscode-codicons).\nFont/icons: CC BY 4.0; code: MIT. Font embedded unchanged in styles.css.\nSee codicons-LICENSE and codicons-LICENSE-CODE.\n");
  const codiconCss = Bun.resolveSync("@vscode/codicons/dist/codicon.css", root);
  const font = Buffer.from(await Bun.file(Bun.resolveSync("@vscode/codicons/dist/codicon.ttf", root)).arrayBuffer()).toString("base64");
  const codicons = (await Bun.file(codiconCss).text()).replace(/url\([^)]+codicon\.ttf[^)]*\)/g, `url("data:font/ttf;base64,${font}")`);
  const result = await postcss([tailwindcss({
    content: [join(root, "src/**/*.{ts,tsx}" )],
    corePlugins: { preflight: true },
    theme: { extend: {} },
  })]).process(`@tailwind base;\n@tailwind components;\n@tailwind utilities;\n${globals}\n${bedrock}\n${codicons}`, { from: undefined });
  await Bun.write(join(root, "dist/styles.css"), `/* Generated by bun run build:css. Do not edit. */\n${result.css}`);
  return result.css;
}
if (import.meta.main) await buildCss();
